[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "ALLOWED_GITHUB_USERNAME,GNEWS_API_KEY,THE_NEWS_API_TOKEN,SUPABASE_SERVICE_ROLE_KEY,REVALIDATE_SECRET,NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_SUPABASE_ANON_KEY,NEXT_PUBLIC_SITE_URL"
  SECRETS_SCAN_OMIT_PATHS = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
